# Generated by Django 2.2.5 on 2019-10-06 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('minimum_price', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('deadline_date', models.DateTimeField(default=datetime.datetime(2019, 10, 7, 0, 26, 52, 274695))),
                ('status', models.CharField(default='Active', max_length=1024)),
            ],
        ),
    ]
