# Generated by Django 2.2.5 on 2019-10-06 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_auctionmodel_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionmodel',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 7, 0, 33, 47, 449249)),
        ),
    ]
