# Generated by Django 2.2.5 on 2019-10-04 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20191003_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionmodel',
            name='deadline',
        ),
        migrations.AddField(
            model_name='auctionmodel',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 14, 32, 14, 22760)),
        ),
    ]
