# Generated by Django 2.2.5 on 2019-10-11 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auto_20191007_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionmodel',
            name='deadline_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 11, 22, 27, 9, 101301)),
        ),
    ]
