# Generated by Django 2.2.5 on 2019-10-13 13:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_auto_20191013_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionmodel',
            name='current_price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='auctionmodel',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
