# Generated by Django 2.2.5 on 2019-10-14 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0006_auto_20191013_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionmodel',
            name='current_price',
        ),
        migrations.CreateModel(
            name='BidModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('new_price', models.FloatField(default=0.0)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auction.AuctionModel')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
