# Generated by Django 2.2.5 on 2019-10-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_auto_20191015_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionmodel',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
