# Generated by Django 2.2.5 on 2019-10-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'This email has been taken'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
