# Generated by Django 2.2.5 on 2019-11-06 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_userlanguage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserLanguage',
            new_name='UserLanguageModel',
        ),
    ]
